
fb_ad_insights_xf:
    constraints:
        unique:
            - id
        not_null:
            - id
            - date_day

fb_ads_xf:
    constraints:
        unique:
            - unique_id
        not_null:
            - unique_id
